### ISSUE TITLE
sql-plugin: paramètres pour un INSERT

### ISSUE THREAD

**Issue by clemzarch** [php-etl/documentation#38]
d'après la doc les paramètres s'ecrivent:
```
query: 'INSERT INTO example VALUES (:id)'
parameters:
    - key: id
       value: '@=input["id"]'
```
mais en realité `key` n'est pas accepté, il faut écrire:
```
query: 'INSERT INTO example VALUES (:id)'
parameters:
    id:
        value: '@=input["id"]'
```
