### ISSUE TITLE
Ajouter la documentation sur "batch"

### ISSUE THREAD

**Issue by clemzarch** [php-etl/documentation#47]
exemple: 
```
        - batch:
            fork:
              foreach: '@=["image"]'
              do: '@={ parent_code: input["parent_code"], combination_code: input["combination_code"], image: input["image"] }'
```
