### ISSUE TITLE
Compléter la doc du connecteur customisé

### ISSUE THREAD

**Issue by sebprt** [php-etl/documentation#55]
Ajouter l'utilisation de factories et appels de méthodes

```yaml
 Kiboko\Magento\V2_3\Client:
  factory:
    class: 'Kiboko\Magento\V2_3\Client'
    method: 'create'
  arguments:
    - '@Http\Client\Common\PluginClient'
```

```yaml
Kiboko\Component\Flow\Magento2\FilterGroup:
  calls:
    - withFilter: [ '@Kiboko\Component\Flow\Magento2\Filter' ]
```
